// Turns the project screenshots and portrait into web-ready WebP files.
//
//   pnpm sam images
//
// Source: the images folder next to the Pencil file (the same screenshots the design
// uses), or SAM_IMAGES=<folder>. Each image is written at 800px and 1600px wide to
// public/images/, and src/content/images.generated.ts records the sizes so every
// <img> can reserve its space before it loads. Outputs are committed; sources are not.
import { mkdir, readdir, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { basename, dirname, extname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = process.env.SAM_IMAGES ?? join(homedir(), 'Documents', 'pencil designs', 'images', 'sam')
const outDir = join(root, 'public', 'images')
const manifestPath = join(root, 'src', 'content', 'images.generated.ts')
const WIDTHS = [800, 1600]

await mkdir(outDir, { recursive: true })

const files = (await readdir(source)).filter((file) => extname(file) === '.png').sort()
const manifest = {}

for (const file of files) {
  const name = basename(file, '.png')
  const image = sharp(join(source, file))
  const { width, height } = await image.metadata()
  const variants = []

  // Never upscale: a small source (the portrait) gets one file at its own width.
  for (const target of WIDTHS.filter((w) => w < width).concat(width < WIDTHS.at(-1) ? [width] : [])) {
    const out = `${name}-${target}.webp`
    await sharp(join(source, file)).resize({ width: target }).webp({ quality: 82 }).toFile(join(outDir, out))
    variants.push({ src: `/images/${out}`, width: target })
  }

  manifest[name] = { width, height, variants }
  console.log(`  ${file.padEnd(28)} ${width}x${height} -> ${variants.map((v) => v.width).join(', ')}`)
}

const banner = '// Generated by scripts/import-images.mjs. Do not edit by hand.\n'
await writeFile(
  manifestPath,
  `${banner}export const images = ${JSON.stringify(manifest, null, 2)} as const\n\nexport type ImageName = keyof typeof images\n`,
)
console.log(`\n${files.length} images -> public/images, manifest -> src/content/images.generated.ts`)
