// Generated by scripts/import-images.mjs. Do not edit; add images there and re-run pnpm assets:images.
export const images = {
  "work/northwind": {
    "src": "generated-1789577323589.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#e8e8d8"
  },
  "work/halden-coffee": {
    "src": "generated-1789577320469.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#d8c8b8"
  },
  "work/orbit-health": {
    "src": "generated-1789577326370.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#e8e8d8"
  },
  "work/kinetic-labs": {
    "src": "generated-1789578363583.png",
    "width": 1376,
    "height": 768,
    "widths": [
      640,
      1024,
      1376
    ],
    "color": "#0828d8"
  },
  "work/atlas-freight": {
    "src": "generated-1789579203190.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#081838"
  },
  "people/amara-okafor": {
    "src": "https://images.unsplash.com/photo-1784926119174-1b471595aa5a?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 2399,
    "widths": [
      96,
      144,
      216
    ],
    "color": "#282828"
  }
} as const

export type ImageName = keyof typeof images
