// Generated by scripts/import-images.mjs. Do not edit; add images there and re-run pnpm assets:images.
export const images = {
  "work/northwind": {
    "src": "generated-1789577323589.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#e8e8d8"
  },
  "work/halden-coffee": {
    "src": "generated-1789577320469.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#d8c8b8"
  },
  "work/orbit-health": {
    "src": "generated-1789577326370.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#e8e8d8"
  },
  "work/kinetic-labs": {
    "src": "generated-1789578363583.png",
    "width": 1376,
    "height": 768,
    "widths": [
      640,
      1024,
      1376
    ],
    "color": "#0828d8"
  },
  "work/atlas-freight": {
    "src": "generated-1789579203190.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#081838"
  },
  "people/amara-okafor": {
    "src": "https://images.unsplash.com/photo-1784926119174-1b471595aa5a?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 2399,
    "widths": [
      96,
      144,
      216
    ],
    "color": "#282828"
  },
  "studio/monday-planning": {
    "src": "generated-1789579395826.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#e8e8e8"
  },
  "insights/launch-is-the-start-line": {
    "src": "generated-1789579506258.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#a8b8c8"
  },
  "insights/headless-or-monolith": {
    "src": "generated-1789579532172.png",
    "width": 1408,
    "height": 768,
    "widths": [
      480,
      800
    ],
    "color": "#b8c8c8"
  },
  "insights/checkout-audit": {
    "src": "generated-1789579522787.png",
    "width": 768,
    "height": 1376,
    "widths": [
      480,
      768
    ],
    "color": "#c8c8d8"
  },
  "insights/design-systems-second-year": {
    "src": "generated-1789579520168.png",
    "width": 1408,
    "height": 768,
    "widths": [
      480,
      800
    ],
    "color": "#b8c8c8"
  },
  "insights/technical-seo-javascript": {
    "src": "generated-1789579525110.png",
    "width": 1408,
    "height": 768,
    "widths": [
      480,
      800
    ],
    "color": "#b8b8c8"
  },
  "insights/build-buy-or-integrate": {
    "src": "generated-1789579529376.png",
    "width": 1408,
    "height": 768,
    "widths": [
      480,
      800
    ],
    "color": "#b8c8d8"
  },
  "insights/website-packages": {
    "src": "generated-1789579530858.png",
    "width": 768,
    "height": 1376,
    "widths": [
      480,
      768
    ],
    "color": "#b8c8c8"
  },
  "case-studies/northwind-hero": {
    "src": "generated-1789579203190.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#081838"
  },
  "case-studies/northwind-dashboard": {
    "src": "cs-northwind-dashboard.png",
    "width": 2560,
    "height": 1106,
    "widths": [
      640,
      1024,
      1600,
      2560
    ],
    "color": "#f8f8f8"
  },
  "case-studies/orbit-health-hero": {
    "src": "generated-1789577326370.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#e8e8d8"
  },
  "case-studies/orbit-health-home": {
    "src": "cs-orbit-screen-home.png",
    "width": 756,
    "height": 1626,
    "widths": [
      320,
      540,
      756
    ],
    "color": "#f8f8f8"
  },
  "case-studies/orbit-health-choose-time": {
    "src": "cs-orbit-screen-choose-time.png",
    "width": 756,
    "height": 1626,
    "widths": [
      320,
      540,
      756
    ],
    "color": "#f8f8f8"
  },
  "case-studies/orbit-health-confirm": {
    "src": "cs-orbit-screen-confirm.png",
    "width": 756,
    "height": 1626,
    "widths": [
      320,
      540,
      756
    ],
    "color": "#f8f8f8"
  },
  "case-studies/orbit-health-booked": {
    "src": "cs-orbit-screen-booked.png",
    "width": 756,
    "height": 1626,
    "widths": [
      320,
      540,
      756
    ],
    "color": "#f8f8f8"
  },
  "case-studies/kinetic-labs-cover": {
    "src": "generated-1789578363583.png",
    "width": 1376,
    "height": 768,
    "widths": [
      640,
      1024,
      1376
    ],
    "color": "#0828d8"
  },
  "case-studies/kinetic-labs-home": {
    "src": "cs-kinetic-hero.png",
    "width": 2560,
    "height": 1426,
    "widths": [
      640,
      1024,
      1600,
      2560
    ],
    "color": "#081828"
  },
  "case-studies/kinetic-labs-before": {
    "src": "cs-kinetic-before.png",
    "width": 1240,
    "height": 746,
    "widths": [
      640,
      1240
    ],
    "color": "#f8f8f8"
  },
  "case-studies/kinetic-labs-after": {
    "src": "cs-kinetic-after.png",
    "width": 1240,
    "height": 746,
    "widths": [
      640,
      1240
    ],
    "color": "#081828"
  },
  "case-studies/halden-coffee-hero": {
    "src": "generated-1789577320469.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#d8c8b8"
  },
  "case-studies/halden-coffee-product": {
    "src": "cs-halden-product.png",
    "width": 2560,
    "height": 1306,
    "widths": [
      640,
      1024,
      1600,
      2560
    ],
    "color": "#f8e8e8"
  },
  "case-studies/aurora-architects-hero": {
    "src": "generated-1789577323589.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#e8e8d8"
  },
  "case-studies/aurora-architects-mark": {
    "src": "cs-aurora-mark.png",
    "width": 2560,
    "height": 1120,
    "widths": [
      640,
      1024,
      1600,
      2560
    ],
    "color": "#183828"
  },
  "case-studies/aurora-architects-mark-mobile": {
    "src": "cs-aurora-mark-mobile.png",
    "width": 1050,
    "height": 2076,
    "widths": [
      700,
      1050
    ],
    "color": "#183828"
  },
  "case-studies/aurora-architects-applications": {
    "src": "cs-aurora-applications.png",
    "width": 2560,
    "height": 1312,
    "widths": [
      640,
      1024,
      1600,
      2560
    ],
    "color": "#b86838"
  },
  "case-studies/aurora-architects-applications-mobile": {
    "src": "cs-aurora-applications-mobile.png",
    "width": 1050,
    "height": 1800,
    "widths": [
      700,
      1050
    ],
    "color": "#b86838"
  },
  "case-studies/atlas-freight-cover": {
    "src": "generated-1789579525110.png",
    "width": 1408,
    "height": 768,
    "widths": [
      640,
      1024,
      1408
    ],
    "color": "#b8b8c8"
  },
  "case-studies/kinetic-labs-home-thumb": {
    "src": "cs-kinetic-template-home.png",
    "width": 827,
    "height": 440,
    "widths": [
      480,
      827
    ],
    "color": "#081828"
  },
  "case-studies/kinetic-labs-home-thumb-mobile": {
    "src": "cs-kinetic-template-home-mobile.png",
    "width": 507,
    "height": 390,
    "widths": [
      340,
      507
    ],
    "color": "#081828"
  },
  "case-studies/kinetic-labs-product-thumb": {
    "src": "cs-kinetic-template-product.png",
    "width": 827,
    "height": 440,
    "widths": [
      480,
      827
    ],
    "color": "#081828"
  },
  "case-studies/kinetic-labs-product-thumb-mobile": {
    "src": "cs-kinetic-template-product-mobile.png",
    "width": 507,
    "height": 390,
    "widths": [
      340,
      507
    ],
    "color": "#081828"
  },
  "case-studies/kinetic-labs-pricing-thumb": {
    "src": "cs-kinetic-template-pricing.png",
    "width": 827,
    "height": 440,
    "widths": [
      480,
      827
    ],
    "color": "#f8f8f8"
  },
  "case-studies/kinetic-labs-pricing-thumb-mobile": {
    "src": "cs-kinetic-template-pricing-mobile.png",
    "width": 507,
    "height": 390,
    "widths": [
      340,
      507
    ],
    "color": "#f8f8f8"
  },
  "case-studies/kinetic-labs-customers-thumb": {
    "src": "cs-kinetic-template-customers.png",
    "width": 827,
    "height": 440,
    "widths": [
      480,
      827
    ],
    "color": "#f8f8f8"
  },
  "case-studies/kinetic-labs-customers-thumb-mobile": {
    "src": "cs-kinetic-template-customers-mobile.png",
    "width": 507,
    "height": 390,
    "widths": [
      340,
      507
    ],
    "color": "#f8f8f8"
  },
  "case-studies/kinetic-labs-docs-thumb": {
    "src": "cs-kinetic-template-docs.png",
    "width": 827,
    "height": 440,
    "widths": [
      480,
      827
    ],
    "color": "#f8f8f8"
  },
  "case-studies/kinetic-labs-docs-thumb-mobile": {
    "src": "cs-kinetic-template-docs-mobile.png",
    "width": 507,
    "height": 390,
    "widths": [
      340,
      507
    ],
    "color": "#f8f8f8"
  },
  "case-studies/kinetic-labs-blog-article-thumb": {
    "src": "cs-kinetic-template-blog-article.png",
    "width": 827,
    "height": 440,
    "widths": [
      480,
      827
    ],
    "color": "#081828"
  },
  "case-studies/kinetic-labs-blog-article-thumb-mobile": {
    "src": "cs-kinetic-template-blog-article-mobile.png",
    "width": 507,
    "height": 390,
    "widths": [
      340,
      507
    ],
    "color": "#081828"
  },
  "team/daniel-mensah": {
    "src": "https://images.unsplash.com/photo-1763745315951-7daac4821af6?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 2312,
    "widths": [
      320,
      480,
      640
    ],
    "color": "#e8e8d8"
  },
  "team/priya-raman": {
    "src": "https://images.unsplash.com/photo-1760552069633-c05f246a5d8c?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 2400,
    "widths": [
      320,
      480,
      640
    ],
    "color": "#485858"
  },
  "team/tom-keller": {
    "src": "https://images.unsplash.com/photo-1601233748618-c0d3963fd030?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 1148,
    "widths": [
      320,
      480,
      640
    ],
    "color": "#689868"
  },
  "team/aisha-bello": {
    "src": "https://images.unsplash.com/photo-1591618828412-c1a160a7fb20?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 1067,
    "widths": [
      320,
      480,
      640
    ],
    "color": "#080808"
  },
  "team/leo-martins": {
    "src": "https://images.unsplash.com/photo-1676131161005-ec2b897f1323?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 1068,
    "widths": [
      320,
      480,
      640
    ],
    "color": "#b8a8a8"
  },
  "team/sofia-lind": {
    "src": "https://images.unsplash.com/photo-1581182830442-e8bc7babbf15?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 1067,
    "widths": [
      320,
      480,
      640
    ],
    "color": "#a8a8a8"
  },
  "team/kwame-asante": {
    "src": "https://images.unsplash.com/photo-1763849049538-5ec4a2729c5d?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 2400,
    "widths": [
      320,
      480,
      640
    ],
    "color": "#180808"
  },
  "team/hannah-cole": {
    "src": "https://images.unsplash.com/photo-1631377307692-36a9b6ae3ef6?fm=jpg&q=90&w=1600&fit=max",
    "width": 1600,
    "height": 2400,
    "widths": [
      320,
      480,
      640
    ],
    "color": "#080808"
  }
} as const

export type ImageName = keyof typeof images
