// Generated by scripts/import-images.mjs. Do not edit by hand.
export const images = {
  "adunyato": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/adunyato-800.webp",
        "width": 800
      },
      {
        "src": "/images/adunyato-1440.webp",
        "width": 1440
      }
    ]
  },
  "dexus-synergy": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/dexus-synergy-800.webp",
        "width": 800
      },
      {
        "src": "/images/dexus-synergy-1440.webp",
        "width": 1440
      }
    ]
  },
  "fluxstride-hero": {
    "width": 1440,
    "height": 740,
    "variants": [
      {
        "src": "/images/fluxstride-hero-800.webp",
        "width": 800
      },
      {
        "src": "/images/fluxstride-hero-1440.webp",
        "width": 1440
      }
    ]
  },
  "fluxstride": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/fluxstride-800.webp",
        "width": 800
      },
      {
        "src": "/images/fluxstride-1440.webp",
        "width": 1440
      }
    ]
  },
  "foodsub": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/foodsub-800.webp",
        "width": 800
      },
      {
        "src": "/images/foodsub-1440.webp",
        "width": 1440
      }
    ]
  },
  "ibiza-ng-hero": {
    "width": 1440,
    "height": 562,
    "variants": [
      {
        "src": "/images/ibiza-ng-hero-800.webp",
        "width": 800
      },
      {
        "src": "/images/ibiza-ng-hero-1440.webp",
        "width": 1440
      }
    ]
  },
  "ibiza-ng": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/ibiza-ng-800.webp",
        "width": 800
      },
      {
        "src": "/images/ibiza-ng-1440.webp",
        "width": 1440
      }
    ]
  },
  "portrait": {
    "width": 148,
    "height": 152,
    "variants": [
      {
        "src": "/images/portrait-148.webp",
        "width": 148
      }
    ]
  },
  "slapa-group": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/slapa-group-800.webp",
        "width": 800
      },
      {
        "src": "/images/slapa-group-1440.webp",
        "width": 1440
      }
    ]
  },
  "slapax": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/slapax-800.webp",
        "width": 800
      },
      {
        "src": "/images/slapax-1440.webp",
        "width": 1440
      }
    ]
  },
  "synthetic-slapa": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/synthetic-slapa-800.webp",
        "width": 800
      },
      {
        "src": "/images/synthetic-slapa-1440.webp",
        "width": 1440
      }
    ]
  },
  "utta-holding": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/utta-holding-800.webp",
        "width": 800
      },
      {
        "src": "/images/utta-holding-1440.webp",
        "width": 1440
      }
    ]
  },
  "utta-token": {
    "width": 1440,
    "height": 900,
    "variants": [
      {
        "src": "/images/utta-token-800.webp",
        "width": 800
      },
      {
        "src": "/images/utta-token-1440.webp",
        "width": 1440
      }
    ]
  }
} as const

export type ImageName = keyof typeof images
