// Turns the client wordmarks in the design's "Trusted by" row into SVG outlines.
//
//   pnpm assets:logos
//
// The design sets each placeholder wordmark in its own typeface (Syne, Fraunces …).
// Shipping five web fonts for one row of logos would be wasteful, so the text is
// converted to vector paths once and written to src/content/logos.generated.ts.
// Real client logos can replace these later: any SVG path with a viewBox works.
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import opentype from 'opentype.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const require = createRequire(import.meta.url)
const outPath = join(root, 'src', 'content', 'logos.generated.ts')

/** PLACEHOLDERS: the client names and styling come from the design mockups. */
const LOGOS = [
  { slug: 'northwind', text: 'Northwind', font: 'inter-tight', weight: 700 },
  { slug: 'halden', text: 'HALDEN', font: 'syne', weight: 700 },
  { slug: 'orbit', text: 'orbit.', font: 'dm-sans', weight: 700 },
  { slug: 'kinetic-labs', text: 'Kinetic Labs', font: 'space-grotesk', weight: 500 },
  { slug: 'meridian', text: 'Meridian', font: 'fraunces', weight: 600, style: 'italic' },
  { slug: 'volta', text: 'VOLTA', font: 'archivo-black', weight: 400 },
]

// Paths are drawn at 100 units per em, so a logo's height in em is viewBox height / 100.
const SIZE = 100

/**
 * Places glyphs one by one with pair kerning. opentype.js's own text shaping chokes
 * on some fonts' contextual substitution tables, and plain wordmarks don't need it.
 */
function layout(face, text, baseline, scale) {
  const path = new opentype.Path()
  let x = 0
  let previous = null
  for (const char of text) {
    const glyph = face.charToGlyph(char)
    if (previous) x += face.getKerningValue(previous, glyph) * scale
    path.extend(glyph.getPath(x, baseline, SIZE))
    x += glyph.advanceWidth * scale
    previous = glyph
  }
  return path
}

/** SVG path data with one decimal. (opentype.js 2.0's toPathData optimiser emits NaN for some glyphs.) */
function pathData(path) {
  const n = (value) => {
    if (!Number.isFinite(value)) throw new Error(`Non-finite coordinate in path: ${value}`)
    return Math.round(value * 10) / 10
  }
  return path.commands
    .map((c) => {
      if (c.type === 'M' || c.type === 'L') return `${c.type}${n(c.x)} ${n(c.y)}`
      if (c.type === 'Q') return `Q${n(c.x1)} ${n(c.y1)} ${n(c.x)} ${n(c.y)}`
      if (c.type === 'C') return `C${n(c.x1)} ${n(c.y1)} ${n(c.x2)} ${n(c.y2)} ${n(c.x)} ${n(c.y)}`
      return 'Z'
    })
    .join('')
}

const logos = []
for (const { slug, text, font, weight, style = 'normal' } of LOGOS) {
  const file = require.resolve(`@fontsource/${font}/files/${font}-latin-${weight}-${style}.woff`)
  const buffer = await readFile(file)
  const face = opentype.parse(buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength))

  const scale = SIZE / face.unitsPerEm
  const ascent = face.ascender * scale
  const descent = -face.descender * scale
  const path = layout(face, text, ascent, scale)
  const box = path.getBoundingBox()

  // Horizontal bounds hug the ink; vertical bounds follow the font's line box,
  // so every logo shares a baseline when laid out in a row, like the design's text.
  const x = Math.floor(box.x1)
  const width = Math.ceil(box.x2) - x
  const height = Math.ceil(ascent + descent)

  logos.push({ slug, name: text, viewBox: `${x} 0 ${width} ${height}`, width, height, d: pathData(path) })
  console.log(`  ${slug}  ${width}×${height}`)
}

await writeFile(
  outPath,
  `// Generated by scripts/build-logos.mjs. Do not edit; change LOGOS there and re-run pnpm assets:logos.
export const clientLogos = ${JSON.stringify(logos, null, 2)} as const
`,
)
console.log(`Wrote ${logos.length} logos.`)
