// Imports the images used by the design into responsive, modern formats.
//
//   pnpm assets:images            convert anything missing
//   pnpm assets:images --force    rebuild everything
//
// For every entry in IMAGES below it writes
//   public/images/<name>-<width>.avif and .webp   (one pair per width)
// and regenerates src/content/images.generated.ts, the typed manifest that
// <Picture name="…"> reads (intrinsic size, widths, placeholder colour).
//
// Sources are either files exported from the Pencil design (the "images" folder
// next to fluxstride.pen; override with DESIGN_IMAGES=<dir>) or remote URLs.
//
// Adding an image: add an entry, run the script, commit the output.
import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const designImages = process.env.DESIGN_IMAGES ?? join(homedir(), 'Documents', 'pencil designs', 'images')
const outDir = join(root, 'public', 'images')
const manifestPath = join(root, 'src', 'content', 'images.generated.ts')
const force = process.argv.includes('--force')

const unsplash = (id) => `https://images.unsplash.com/${id}?fm=jpg&q=90&w=1600&fit=max`

/**
 * name → { src, widths? }. `src` is a file name in the design's images folder or a URL.
 * Widths default to [640, 1024, 1408] and are capped at the source width.
 * PLACEHOLDERS: every image here is design-stage artwork or stock photography.
 */
const IMAGES = {
  'work/northwind': { src: 'generated-1789577323589.png' },
  'work/halden-coffee': { src: 'generated-1789577320469.png' },
  'work/orbit-health': { src: 'generated-1789577326370.png' },
  'work/kinetic-labs': { src: 'generated-1789578363583.png' },
  'work/atlas-freight': { src: 'generated-1789579203190.png' },
  'people/amara-okafor': { src: unsplash('photo-1784926119174-1b471595aa5a'), widths: [96, 144, 216] },
}

const DEFAULT_WIDTHS = [640, 1024, 1408]

async function load(src) {
  if (/^https?:\/\//.test(src)) {
    const response = await fetch(src)
    if (!response.ok) throw new Error(`${response.status} fetching ${src}`)
    return Buffer.from(await response.arrayBuffer())
  }
  const path = join(designImages, src)
  if (!existsSync(path)) throw new Error(`Missing ${path}. Set DESIGN_IMAGES to the design's images folder.`)
  return readFile(path)
}

function hex({ r, g, b }) {
  return `#${[r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('')}`
}

async function readManifest() {
  if (!existsSync(manifestPath)) return {}
  const text = await readFile(manifestPath, 'utf8')
  const json = text.match(/export const images = (\{[\s\S]*\}) as const/)
  return json ? JSON.parse(json[1]) : {}
}

const previous = await readManifest()
const manifest = {}
let converted = 0

for (const [name, { src, widths = DEFAULT_WIDTHS }] of Object.entries(IMAGES)) {
  const known = previous[name]
  const outputs = (list) =>
    list.flatMap((w) => ['avif', 'webp'].map((ext) => join(outDir, `${name}-${w}.${ext}`)))

  if (!force && known && known.src === src && outputs(known.widths).every((file) => existsSync(file))) {
    manifest[name] = known
    continue
  }

  const input = await load(src)
  const image = sharp(input).rotate()
  const { width, height } = await image.metadata()
  const { dominant } = await image.stats()
  const sizes = [...new Set(widths.map((w) => Math.min(w, width)))].sort((a, b) => a - b)

  await mkdir(dirname(join(outDir, name)), { recursive: true })
  for (const w of sizes) {
    const resized = sharp(input).rotate().resize({ width: w, withoutEnlargement: true })
    await resized
      .clone()
      .avif({ quality: 55, effort: 6 })
      .toFile(join(outDir, `${name}-${w}.avif`))
    await resized
      .clone()
      .webp({ quality: 78, effort: 6 })
      .toFile(join(outDir, `${name}-${w}.webp`))
  }

  manifest[name] = { src, width, height, widths: sizes, color: hex(dominant) }
  converted++
  console.log(`  ${name}  ${width}×${height} → ${sizes.join(', ')}`)
}

const body = JSON.stringify(manifest, null, 2)
await writeFile(
  manifestPath,
  `// Generated by scripts/import-images.mjs. Do not edit; add images there and re-run pnpm assets:images.
export const images = ${body} as const

export type ImageName = keyof typeof images
`,
)
console.log(`${converted} converted, ${Object.keys(manifest).length - converted} unchanged.`)
